oracle/bft-consensus-agda

CONTRIBUTING.md, LibraBFT/Abstract/RecordChain/Properties.agda, LibraBFT/Yasm/System.agda, README.md, TODO.md
=> Minor edits, including putting contributor list on front page

LibraBFT/Abstract/RecordChain/Properties.agda
Just reordering parameters of some related lemmas to make the correspondence clearer, and improve some misleading names.
=> Reordering and renaming for clarity

LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Impl/Properties/VotesOnceDirect.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda
Proved the VotesOnceDirect with auxiliary lemmas. Some of these auxiliary lemmas are not proved yet.
=> Progress on VotesOnceDirect

LibraBFT/Base/KVMap.agda, LibraBFT/Base/PKCS.agda, LibraBFT/Base/Util.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/PreferredRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/Records.agda, LibraBFT/Concrete/System.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/Types.agda, LibraBFT/Impl/Consensus/Types/EpochDep.agda, LibraBFT/Impl/Consensus/Types/EpochIndep.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/NetworkMsg.agda, LibraBFT/Impl/Properties/Aux.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Impl/Properties/VotesOnceDirect.agda, LibraBFT/Impl/Util/RWST.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda
After the changes in initialisation the proof of `VotesOnceDirect` on implementation side was broken. In this pull request the proof of `VotesOnceDirect` was fixed. therefore we have again and inductive proof of `VotesOnlyOnce` rule.
=> Proved `VotesOnceDirect`

LibraBFT/Base/KVMap.agda, LibraBFT/Impl/Consensus/ConsensusTypes/TimeoutCertificate.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Vote.agda, LibraBFT/Impl/Consensus/Types.agda, LibraBFT/Impl/Consensus/Types/EpochIndep.agda, LibraBFT/Impl/Consensus/Types/PendingVotes.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle.agda.orig, LibraBFT/Impl/Types/CryptoProxies.agda, LibraBFT/Impl/Types/LedgerInfoWithSignatures.agda, LibraBFT/Impl/Types/ValidatorVerifier.agda, LibraBFT/Impl/Util/Util.agda, LibraBFT/Prelude.agda
Proofs/tests of this module will follow.
But I would like feedback and after incorporating feedback, to squash/commit this to main.
=> pending votes implementation

LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/Records.agda, LibraBFT/Concrete/System.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/Types/PendingVotesSpec.agda, LibraBFT/ImplFake/Consensus/RoundManager.agda, LibraBFT/ImplFake/Consensus/RoundManager/Properties.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplFake/Handle.agda.orig, LibraBFT/ImplFake/Handle/Properties.agda, LibraBFT/ImplFake/NetworkMsg.agda, LibraBFT/ImplFake/Properties/PreferredRound.agda, LibraBFT/ImplFake/Properties/VotesOnce.agda, LibraBFT/ImplFake/Properties/VotesOnceDirect.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochDep.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Consensus/Types/MetaEpochIndep.agda, LibraBFT/ImplShared/Util/Crypto.agda, LibraBFT/ImplShared/Util/Util.agda
These change are on the b7317d2 chris-process-proposal branch.
I'm out, so if any discussion/changes required, please handle that while I'm gone.
=> replace ₋ with _ (underscore)

LibraBFT/Impl/Consensus/Liveness/Properties/ProposerElection.agda, LibraBFT/Prelude.agda
There are two versions of the proof in two commits.  I think/hope I am missing something to make this more streamlined, so I am sharing for discussion and improvement.  I'd like to improve and document this more before merging.
=> A couple of proofs of `IsValidProposalM.contract`, room for improvement!

LibraBFT/Concrete/Properties/Common.agda, LibraBFT/Concrete/Properties/PreferredRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda
Proved the postulate `NewVoteRound≢0`
=> Proved Postulate NewVoteRound≢0

LibraBFT/Prelude.agda
Just a small PR to generalize `foldrM` and `forM_` to different levels.
=> LibraBFT: Prelude: make foldrM and forM_ level-polymorphic

LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/Network.agda, LibraBFT/Impl/Execution/ExecutorTypes/StateComputeResult.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
; Signed-off-by: Harold Carr harold.carr@oracle.com
=> implemented liNextEpochState, qcEndsEpoch

LibraBFT/Impl/Consensus/ConsensusTypes/Block.agda, LibraBFT/Impl/Consensus/Liveness/ProposalGenerator.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/ImplShared/Util/Crypto.agda
- `RoundManager`
- added `processNewRoundEventM`, `generateProposalM`
- `ProposalGenerator`
- postulate `generateProposalM`
- `Block`
- added `newProposalFromBlockDataAndSignature`
- `SafetyRules`
- added `signProposalM`, `verifyAuthorM`
- `Output`
- made `BroadcastProposal` take a list of authors (like Haskell)
- `Crypto`
- added `hashBD`
- `Types`
- added `rmObmAllAuthors`
=> added RoundManager processNewRoundEventM, generateProposalM and friends

LibraBFT/Impl/Consensus/ConsensusTypes/BlockData.agda, LibraBFT/Impl/Consensus/Liveness/ProposalGenerator.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Types/BlockInfo.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
- `ProposalGenerator`
- add `generateProposalM`, `ensureHighestQuorumCertM`
- `EpochIndep`
- add `ProposalGenerator` record
- `Types`
- add `ProposalGenerator` to `RoundManager` record
- add `lProposalGenerator`
- `Handle` (`Impl` and `ImplFake`)
- add and use `initPG`
- `BlockInfo`
- add `hasReconfiguration`
- `BlockData`
- add `newProposal`
=> implemented ProposalGenerator.generateProposalM

LibraBFT/Impl/Consensus/ConsensusTypes/VoteMsg.agda, LibraBFT/Impl/Consensus/Network.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
* Minor formatting/ordering
* Add `siEpoch` Lens and `lcheck`
* Eliminate some unnecessary and misleading variable names
* Simplification by pattern matching on `refl`
=> Minor additions/edits for chris-votes-once

LibraBFT/Impl/Consensus/ConsensusTypes/VoteMsg.agda, LibraBFT/Impl/Consensus/Network.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
A small PR to include some of @mark-moir 's updates to the implementation that were merged into `chris-votes-once`
=> Cherry pick some commits for `Network` process proposal / vote, `lcheck` in `VoteMsg`

LibraBFT/Concrete/System/Parameters.agda, LibraBFT/ImplShared/Util/Crypto.agda
=> added TODO about modeling haskell hashing; 

LibraBFT/Impl/Consensus/Liveness/ProposalGenerator.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
This makes getter only lens "weird" again.
Note : this PR is not against main - it is against harold-RoundManager-processSyncInfoM-processLocalTimeouotM
=> "getter only" lens

LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda
This PR addresses most of the comments in my latest review on #79.
=> Only minor style, renaming, comments, etc. addressing most review comments on #79

LibraBFT/Base/Util.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/Common.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplFake/Handle/Properties.agda, LibraBFT/ImplFake/Properties/PreferredRound.agda, LibraBFT/ImplFake/Properties/VotesOnce.agda, LibraBFT/ImplFake/Properties/VotesOnceDirect.agda, LibraBFT/ImplShared/NetworkMsg.agda
Best to read one commit at a time, I think.
=> Progress on system-level invariant, `Contract`s and `Requirements` needed for `qcVoteSigsSentB4` plus progress on that

LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Consensus/PendingVotes.agda, LibraBFT/Impl/Consensus/PendingVotesSpec.agda
=> move PendingVotes*  to correct module

LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/ImplShared/Consensus/Types.agda
this addresses review comments from @mark-moir for 
https://github.com/oracle/bft-consensus-agda/pull/97
=> comment out logEE usage; fix comparison condition

LibraBFT/Impl/Consensus/ConsensusTypes/Block.agda, LibraBFT/Impl/Consensus/ConsensusTypes/BlockData.agda, LibraBFT/Impl/Consensus/ConsensusTypes/ProposalMsg.agda, LibraBFT/Impl/Consensus/ConsensusTypes/SyncInfo.agda, LibraBFT/Impl/Consensus/ConsensusTypes/TimeoutCertificate.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Vote.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/OBM/Crypto.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Util/RWST/Syntax.agda, LibraBFT/Prelude.agda
various verify/validate/wellFormed, such as:
Block.verifyWellFormed
Block.validateSignature
Vote.verify
Vote.addTimeoutSignature
ProposalMsg.verifyWellFormed
ProposalMsg.verify
TimeoutCertificate.verify
SyncInfo.verify
Note: this postulates : payloadIsEmpty : when we do Epoch change, we will need to decide what empty is.
=> implement more verify/validate

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Handle/Properties.agda, Optics/Functorial.agda
Also some refinements to the contracts for `RoundManager` peer handlers, and a small cleanup in one of the `Handler` proofs.
=> Progress on contract for `executeAndInsertBlockE`

LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda
Refactored contract' of verifyQcMSpec module in SafetyRules properties
=> Refactoring SafetyRules property

LibraBFT/Base/KVMap.agda, LibraBFT/Impl/Consensus/PersistentLivenessStorage.agda, LibraBFT/Impl/Consensus/TestUtils/MockStorage.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/Prelude.agda
Implemented all functions that are used in Agda at this time.
=> implement persistent liveness storage

LibraBFT/Impl/Consensus/Liveness/ExponentialTimeInterval.agda, LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/OBM/ConfigHardCoded.agda, LibraBFT/Impl/OBM/Init.agda, LibraBFT/Impl/OBM/Rust/RustTypes.agda, LibraBFT/Impl/OBM/Time.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/Prelude.agda
- ExponentialTimeInterval NEW FILE
- RoundState
- implement setupTimeoutM, setupDeadlineM, roundIndexAfterCommittedRound, getRoundDuration
- postulate _**_, ceiling
- Impl/Handle
- update initRS
- ImplFake/Handle.agda
- update initRS
- ConfigHardCoded NEW FILE
- Impl/OBM/Init NEW FILE
- Duration
- postulate fromMillis, asMillis
- RustTypes
- added F64, U128
- Impl/OBM/Time NEW FILE
- ImplShared/Consensus/Types
- added ExponentialTimeInterval, RoundStateTimeInterval
- added fields to RoundState
- LibraBFT.Prelude
- added min alias
=> implemented RoundState.setupTimeoutM

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/EpochManager.agda, LibraBFT/Impl/Consensus/EpochManagerTypes.agda, LibraBFT/Impl/Consensus/MetricsSafetyRules.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/SafetyRules/PersistentSafetyStorage.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRulesManager.agda, LibraBFT/Impl/Consensus/TestUtils/MockStorage.agda, LibraBFT/Impl/OBM/ECP-LBFT-OBM-Diff/ECP-LBFT-OBM-Diff-1.agda, LibraBFT/Impl/Storage/DiemDB/DiemDB.agda, LibraBFT/Impl/Types/BlockInfo.agda, LibraBFT/Impl/Types/EpochChangeProof.agda, LibraBFT/Impl/Types/ValidatorVerifier.agda, LibraBFT/Impl/Types/Verifier.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/Prelude.agda
The main file is `EpochManager.agda`.
Everything else is support (including lots of postulated functions).
Work on the postulated functions will happen is a subsequent pull request.
=> implemented EpochManager

LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/OBM/ECP-LBFT-OBM-Diff/ECP-LBFT-OBM-Diff-1.agda, LibraBFT/Impl/OBM/ECP-LBFT-OBM-Diff/ECP-LBFT-OBM-Diff-2.agda, LibraBFT/Impl/Types/EpochChangeProof.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/Prelude.agda
This completes (well, there are some TODO for `Broadcast`) the OBM specific changes to epoch change.
I'll handle the Broadcast stuff in a subsequent pull request.
=> more epoch change

LibraBFT/Abstract/Types/EpochConfig.agda, LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/Common.agda, LibraBFT/Concrete/Properties/PreferredRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle/InitProperties.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/GenKeyFile.agda, LibraBFT/Impl/Properties/Common.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplFake/Handle/Properties.agda, LibraBFT/ImplFake/Properties.agda, LibraBFT/ImplFake/Properties/VotesOnce.agda, LibraBFT/ImplFake/Properties/VotesOnceDirect.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochDep.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda
Yasm/Base
- change init to return Maybe
- rename init to bootstrap
Rename genesis-like names to bootstrap* names.
=> Yasm/Base init return Maybe; rename Genesis to Bootstrap

LibraBFT/Concrete/Properties.agda
=> Comment on generalising Concrete modules, not worthwhile at this point

docs/PeerHandlerContracts.org
Slightly edited prose, disclaimer about zero-width whitespaces (and added more of those)
=> Minor changes to PeerHandlerContract documentation

src/Dijkstra/RWS.agda, src/Haskell/Modules/RWS.agda, src/LibraBFT/Impl/Consensus/EpochManager.agda, src/LibraBFT/Impl/Properties/Util.agda, src/LibraBFT/ImplShared/LBFT.agda, src/Util/Lemmas.agda
=> Rename `runRWS` to `RWS-run` for consistency, move `++-NoneOfKind` to lemmas

src/Dijkstra/AST/Maybe.agda
We can discuss this solution in the meeting today, if desired.
Signed-off-by: Christa Jenkins <chris.w.jenkins@oracle.com>
=> Dijkstra: AST: Maybe: proof that div works

src/Dijkstra/AST/Either.agda
No time for more description at the moment
=> Add `AST` variant of `Either`, prove properties

src/Dijkstra/AST/Core.agda, src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Maybe.agda
=> Minor tweaks and comments on `AST` framework and use cases (`Either` and `Maybe`)

docs/README.org
=> Add link to extended version of NASA 2022 paper

docs/README.org
=> Add link to short syntax paper

src/Dijkstra/AST/Maybe.agda
The PR proves the previously-postulated `maybePTApp` property, via a new proof that `predTrans MaybePT` really is the weakest precondition for a `MaybeD` program.
=> Prove `maybePTApp`

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Examples/Maybe/Branching.agda, src/Dijkstra/AST/Maybe.agda
* Adds support for `maybe` in branching extensions
* Extends `AST EitherOps` with branch branching support and syntax
* Comments and formatting in response to feedback on #209
=> Add branching support for `maybe` and extend `Either` with branching operations

src/Dijkstra/AST/Either.agda
=> either pt is weakest

src/Dijkstra/AST/Examples/RWS.agda
The main purpose of this PR is to tweak @haroldcarr 😝.  As a side effect, it slightly simplifies the new `RWS` example.  It is best reviewed one commit at a time.
=> Simplify `RWS` example, twice

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Core.agda, src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Maybe.agda, src/Dijkstra/AST/RWS.agda
=> Updated Either and Maybe ASTPredTransMono.   Reformatted RWS ASTPredTransMono.

src/Dijkstra/AST/Branching.agda
=> More opening and aligning

src/Dijkstra/AST/Branching.agda
=> Yet more opening and aligning to make the paper prettier and keep consistent

src/Dijkstra/AST/Branching.agda
=> More aligning, last one before merging to `main-ast`

src/Dijkstra/AST/Examples/PaperIntro.agda
=> Make example use names consistent with the paper

README.md, src/LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda
=> Update repo structure description, fix links
