LibraBFT/Abstract/BFT.agda, LibraBFT/Abstract/Properties.agda, LibraBFT/Abstract/RecordChain.agda, LibraBFT/Abstract/RecordChain/Invariants.agda, LibraBFT/Abstract/RecordChain/Properties.agda, LibraBFT/Abstract/Records.agda, LibraBFT/Abstract/Records/Extends.agda, LibraBFT/Abstract/Types.agda, LibraBFT/Impl/Consensus/Types/EpochDep.agda
Remove almost all mentions of Hash from abstract namespace, where we care only about an opaque `UID` type.  The type of `initialAgreeHash` (now renamed to `genesisUID`) remains `Hash`, as there is still a `TODO` to do the module parameter refactoring needed to provide a `UID` type to `LibraBFT.Abstract.Types`, enabling `genesisUID` to be of this type.
=> (Mostly) isolate hash (a concrete notion) from Abstract namespace

LibraBFT/Abstract/Properties.agda, LibraBFT/Abstract/RecordChain/Invariants.agda, LibraBFT/Abstract/RecordChain/Properties.agda
Our abstract `LockedRoundRule` (similar to the corresponding aspects of HotStuff and LibraBDT papers) imposes a condition on peers that is stronger than necessary.  In particular, the risk that this rule is designed to avoid is if a block is committed, we must ensure that a conflicting block is not also committed.  The first block is committed only if the 3-chain mentioned in the condition has contiguous rounds, but this was not stated.  This pull request fixes that.
By weakening the constraint, we demonstrate that a wider range of implementations is possible.  It is unclear whether it would be advantageous to modify existing implementations to take advantage of the weaker requirement, but it is worth knowing that we can do so without compromising correctness.
We also eliminate a …
=> Only require LockedRoundRule for contiguous 3-chain, eliminate TERMINATING

LibraBFT/Abstract/BFT.agda, LibraBFT/Abstract/Obligations/LockedRound.agda, LibraBFT/Abstract/Obligations/VotesOnce.agda, LibraBFT/Abstract/Properties.agda, LibraBFT/Abstract/RecordChain/Assumptions.agda, LibraBFT/Abstract/RecordChain/Properties.agda, LibraBFT/Abstract/Records.agda, LibraBFT/Abstract/Types.agda, LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/LockedRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/Records.agda, LibraBFT/Impl/Consensus/Types.agda, LibraBFT/Impl/Consensus/Types/EpochDep.agda, LibraBFT/Lemmas.agda, LibraBFT/Yasm/AvailableEpochs.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda
So far, our abstract `EpochConfig` has baked in assumptions about the number of peers, maximum assumed faulty, and quorum size.  This is fundamentally a "one peer, one vote" regime, but some implementations, including LIbraBFT assign quorums differently (LibraBFT assigns Voting Power to peers, perhaps not uniformly, and requires a quorum to exceed a threshold of voting power).
This pull request generalizes `EpochConfig` so that the implementation provides an `IsQuorum` predicate on lists of members, and a property that says that, given any two such lists that both satisfy `IsQuorum`, there is an honest peer in their intersection.
Because `EpochConfig` includes a predicate on lists of members, `EpochConfig` becomes `Set₁`, which propagates around quite a bit.
There is one hole left to be …
=> Generalize EpochConfig to enable more flexible quorum definitions

LibraBFT/Abstract/BFT.agda, LibraBFT/Base/PKCS.agda, LibraBFT/Impl/Consensus/Types/EpochDep.agda, LibraBFT/Prelude.agda
Proved the well-known result that for `N` peers of which at most `f` are byzantine, for any two lists of at least `N - f` different peers, there is at least one honest peer in their intersection.
This can be a utility for someone trying to create an abstract `EpochConfig` for an implementation that assumes one peer, one vote. 
Also completed the hole in `IsValidQC` using `All-reduce` function.
=> Proved bft-lemma for one peer, one vote and completed IsValidQC

LibraBFT/Abstract/RecordChain/Assumptions.agda, LibraBFT/Abstract/System.agda, LibraBFT/Abstract/Types.agda, LibraBFT/Concrete/Intermediate.agda, LibraBFT/Concrete/Obligations/LockedRound.agda, LibraBFT/Concrete/Obligations/VotesOnce.agda, LibraBFT/Concrete/System.agda
Enable opening an inner module to avoid specifying the `EpochConfig` explicitly for `Meta-Honest-Member`. This is to enable consistency with the paper without cluttering the paper with the `EpochConfig`.
=> For consistency with paper, minor refactor and remove unneeded names

LibraBFT/Abstract/RecordChain/Assumptions.agda
Use `v` and `v'` consistently, eliminate `va` and `va'`.  For consistency with paper.
=> Minor renaming for consistency with paper

LibraBFT/Abstract/Properties.agda
Remove obsolete imports and pragma, which break the abstraction boundary and call into question whether the proofs are really finished.
=> Remove obsolete imports and pragma

LibraBFT/Abstract/BFT.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda
Proved the bft-lemma for a set of nodes of that can have different voting power. The module receives as module parameter a function `votPower` that returns for each member its voting power.  The (inner) module also receives as arguments proof that that the combined power of all nodes is `N` and the combined voting power of the byzantine nodes has a threshold of `bizF`. 
The bft-lemma (at the end of the file) receives two lists of distinct members (enforced by the type `IsSorted _<Fin_`) such that, for each list, the combined voting power of all members in that list is at least than `N - bizF` (representing the quorum size). 
This work can be used as a utility for a possible implementation of LibraBFT.
=> Lis bft lemma pr

CONTRIBUTING.md, LibraBFT/Base/Types.agda, LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/LockedRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/System.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Impl/Properties.agda, LibraBFT/Impl/Properties/Aux.agda, LibraBFT/Impl/Properties/LockedRound.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda, LibraBFT/Yasm/AvailableEpochs.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda, LibraBFT/Yasm/Yasm.agda, STYLE.md
During development, we used the `EpochConfig` type from `LibraBFT.Abstract` in the system model (`Yasm`).  This was an abstraction violation because the system model should be independent of any particular application.  Similarly, we assumed `NodeId` was `ℕ` (as in our fake implementation).
This pull request abstracts out only the necessary parts of `EpochConfig` for the system model and parameterizes the system model by a `PeerId` type.
It also includes some updates to the Style and Contributing guides to try to move towards some conventions for module organization.
=> Tease SystemModel apart from LibraBFT types, move towards standard module conventions

LibraBFT/Abstract/BFT.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda
Addressed `TODO-1` of proving bft-lemma using the `allDistinct` data type instead of the `IsSorted` used before.
=> Proved bft-lemma using allDistinct

LibraBFT/Abstract/Types/EpochConfig.agda, LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/LockedRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/System.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Impl/Properties/Aux.agda, LibraBFT/Yasm/AvailableEpochs.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda, LibraBFT/Yasm/Yasm.agda
This pull request:
* Eliminates an unintentionally duplicated `NodeId` type
* Generalises the system model by eliminating the assumption that each peer in an epoch can sign new messages for exactly one public key, replacing this with a predicate over peers and public keys
* Adds some properties that will be used in future proofs, namely:
*  `lookup-𝓔s-injective`
*  `sameEpoch⇒sameEC`
*  `cheatStepDNMPeerStates` (postulated, for now)
*  `peersRemainInitialized` (postulated, for now)
*  `Any-Step-⇒`
* Minor renaming for intuition
=> Generalize system model, eliminate duplicated `NodeId` type and add some properties

LibraBFT/Concrete/Records.agda, LibraBFT/Concrete/System.agda, LibraBFT/Impl/Consensus/ChainedBFT/EventProcessor/Properties.agda, LibraBFT/Impl/Consensus/Types.agda, LibraBFT/Impl/Consensus/Types/EpochIndep.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/NetworkMsg.agda, LibraBFT/Impl/Properties/Aux.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Impl/Util/Util.agda
This pull request supersedes #2.  It proves the two implementation obligations for `VotesOnce`.  One (`vo₁`) says that if a handler sends a new vote for a given epoch and round as a previous vote for the same epoch and round signed for the same honest public key, then it is for the same `blockID`.  The other (`vo₂`) says that if a handler sends two votes for the same epoch and round, then they are for the same `blockID`.  (In fact, our fake implementation does not send multiple votes for the same epoch and round, so the proofs are contradictions, but this helps us put the pieces together before we start proofs for a more complete implementation model.)
The proof of `vo₁` demonstrates the use of `unwind` to find where a signature is first introduced, and then proving it establishes a …
=> Prove `VotesOnce` properties for fake implementation

LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/System.agda
Proved the following postulates on the `LibraBFT.Yasm.System`:
- `cheatStepDNMPeerStates`
- `msgs-stable`
- `sendMessages-target`
- `peersRemainInitialized`
In order to prove the last one I needed to add a new parameter to the `SystemParameters` which is a `Decidable` over `PeerId`. Actually, I think that this new parameter will also be useful for some other lemmas that we may need to prove in future.
=> Proved postulates on System model

LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Impl/Base/Types.agda, LibraBFT/Impl/Consensus/Types.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/NetworkMsg.agda, LibraBFT/Impl/Properties/Aux.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Impl/Util/Util.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda
* Replace last two parameters of `StepPeerState` with a pair, matching handler out put type
* Other minor changes to `Yasm` for convenience
* Factor "generic" parts of `vo1` proof into `Yasm.Properties`, redo proof
* Revise and prove postulated properties used by the `vo1` proof
=> Refactor some general parts of `vo1` proof into system model, fix proofs, minor system model changes for convenience

LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda, LibraBFT/Yasm/Yasm.agda, Util/FunctionOverride.agda
This is an experimental change to our system model, in which `peerStates` becomes a total function from `PeerId` to `PeerState`, meaning that even peers that don't exist yet have a "state".
This change eliminates having to deal with `Maybe PeerState` all the time, but also we cannot prove anything about the state of an uninitialised peer and we cannot distinguish them from initialised ones.
To address this issue, we also introduce a new element to `SystemState` called `initialised`, which tracks which peers' states have been initialised.  We can then state/prove properties about initialised peer states.  An example is the (postulated, for now) `qcVotesSentB4` property, which is required to hold only for initialised peers.
There are also a few minor unrelated changes.  For one example, the …
=> Make `peerStates` total, eliminate pain dealing with `Maybe PeerState`

LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Yasm/Properties.agda
Managed to simplify the `VotesOnlyOnce` property on the concrete side. This property states that for any two votes `v` and `v'`, cast by an honest `α`, in the message pool of a state `st`, if `v` and `v'` have equal rounds and epochs, then they vote for the same block.
In order to achieve that we defined a new lemma called `newMsg⊎msgSent4` that for every message in the message pool of a post-state returns evidence that either is a new valid message for the peer taking the step or that some message with the same signature was sent before. Given that, to prove the `VotesOnlyOnce` property for the `StepPeerState` we just need to split the proof in 4 possibilities (as before):
- `v` and `v'` were already present in the msgPool before -> use induction hypothesis
- `v` and `v'` are both in the …
=> Simplified VotesOnlyOnce property on the concrete side

LibraBFT/Base/ByteString.agda, LibraBFT/Base/Encode.agda, LibraBFT/Impl/Consensus/Types/EpochIndep.agda, LibraBFT/Impl/Properties/VotesOnceDirect.agda, LibraBFT/Yasm/System.agda
The constructor for `SyncInfo` compares two `QuorumCert`s and constructs the `SyncInfo` dependent on the outcome.  We observe that `QuorumCert` has (postulated, for now) an injective encoding, and we can implement decidable equality for any such type.
This pull request provides support for that and then uses it to implement the constructor and lens for `SyncInfo`.  This avoids the need to manually implement decidable equality  for `QuorumCert`, `VoteData`, `BlockInfo`, `LedgerInfoWithSignatures`, etc.
=> Add decidable equality for any type with an `Encoder`, use it to implement conditional `SyncInfo` constructor and lens

LibraBFT/Impl/Consensus/Types/EpochIndep.agda, LibraBFT/Impl/NetworkMsg.agda
=> rename CommitMsg fields from c* to cm* (for code consistency)

LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/Properties/VotesOnce.agda
Some nice simplifications enabled by @lisandrasilva's alternative proof of the same property.  Specifically, Agda can figure out that `processProposalMsg` sends only one vote, so by matching on the evidence that a vote is in the outputs of that function, we can eliminate a bunch of other reasoning about it.
Also fixed a small oversight made in response to review comments on the previous pull request.
=> Simplify LibraBFT.Impl.Properties.VotesOnce` inspired by alternative proof in `VotesOnceDirect`

LibraBFT/Abstract/Types/EpochConfig.agda, LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Obligations/PreferredRound.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/PreferredRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/Records.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/Properties.agda, LibraBFT/Impl/Properties/PreferredRound.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Impl/Properties/VotesOnceDirect.agda, LibraBFT/Lemmas.agda, LibraBFT/Yasm/Yasm.agda
- The main purpose of this pull request is to define the implementation obligations related to the `PreferredRound` rule (`LibraBFT.Concrete.Properties.PreferredRound`), so that, assuming an implementation complies with these obligations, we can prove `LibraBFT.Concrete.Obligations.PreferredRound.Type` for our intermediate system state, and we have already proved (`LibraBFT.Concrete.Obligations.PreferredRound.proof`) that this implies the corresponding assumption made by the abstract proofs.
- The new implementation obligations refer to structures such as `Cand-3-chain-vote` and `VoteParentData`, which are in terms of abstract `Record`s and therefore require an `EpochConfig`, which is introduced as a module parameter.  For consistency, the `VoteOnce` obligations now similarly receive an …
=> Define implementation obligations for `PreferredRound` rule

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Vote.agda, LibraBFT/Impl/Consensus/Liveness/ProposerElection.agda, LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/Types.agda, LibraBFT/Impl/Consensus/Types/EpochIndep.agda, LibraBFT/Impl/Consensus/Types/PendingVotesSpec.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/OBM/Prelude.agda, LibraBFT/Impl/Types/ValidatorSigner.agda, LibraBFT/Impl/Util/RWST.agda
This contains an incomplete implementation of `RoundManager.processVoteMsgM`.
If it is needed before I am available again, go ahead and complete it.  Otherwise, it is fine to leave it as is.
There are places in this request that have `IMPL-TODO` - it would be good to have feedback/fixes for those places.
=> parts of process vote; PendingVotesSpec (not used)

LibraBFT/Concrete/Intermediate.agda, LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/PreferredRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/System.agda, LibraBFT/Concrete/System/Parameters.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplFake/Handle/Properties.agda, LibraBFT/ImplFake/Properties.agda, LibraBFT/ImplFake/Properties/PreferredRound.agda, LibraBFT/ImplFake/Properties/VotesOnce.agda, LibraBFT/ImplFake/Properties/VotesOnceDirect.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Util/HashCollisions.agda, LibraBFT/Yasm/Base.agda, LibraBFT/Yasm/Properties.agda, LibraBFT/Yasm/System.agda, LibraBFT/Yasm/Yasm.agda
The main purpose of this PR is to enable us to hook up the under-development implementation model to the concrete properties without breaking or losing our fake implementation and proofs about it.  This further enables proving multiple variants on an implementation.  The main changes are:
* Refactor `Yasm` so that we first instantiate it with the types, and subsequently instantiate it with initialisation information and handlers.
* Tease apart `Concrete` namespace from `Impl*`, so that anything it needs to know about an implementation is provided as a module parameter, not directly from an implementation as it did before.
* As a result, there is one new proof (`NewVoteRound≢0`) required in `LibraBFT.Concrete.Properties.VotesOnce` and an implementation obligation is provided about honest …
=> Refactor so we can use different implementation handlers (e.g. fake and real) with the same underlying types

LibraBFT/Impl/Consensus/Network.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/IO/OBM/InputOutputHandlers.agda, LibraBFT/Impl/OBM/Logging/Logging.agda, LibraBFT/ImplFake/Consensus/RoundManager.agda, LibraBFT/ImplFake/Consensus/RoundManager/Properties.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/ImplShared/Util/Util.agda
This PR refactors some of the types and functions defined with the `FakeImpl` handler into `ImplShared` to enable them to be used also by the real implementation model.  It further begins modeling the actual network handlers so we can see where to connect the pieces.
=> Refactor `Output` and friends to `ImplShared`, start modeling network handlers

LibraBFT/ImplShared/Consensus/Types.agda
Just a small amendment to this comment. One of the examples, (`bs <- gets rmGetBlockStore`) would not have been well-typed.
=> LibraBFT: ImplShared: Consensus: Types: amend NO-DEPENDENT-LENSES comment

LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/Common.agda, LibraBFT/Concrete/Properties/PreferredRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/ImplFake/Handle/Properties.agda, LibraBFT/ImplFake/Properties/VotesOnce.agda
This PR applies a few minor changes resulting from the review of #43, and also reinstates and fixes the previously  broken proof for `FakeImpl.Properties.VotesOnce.vo₁`.
=> Small merge review changes from #43, reinstate and fix `FakeImpl.Properties.VotesOnce.vo₁` proof

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Block.agda, LibraBFT/Impl/Consensus/ConsensusTypes/QuorumCert.agda, LibraBFT/Impl/Consensus/Network.agda, LibraBFT/Impl/Consensus/PersistentLivenessStorage.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/Consensus/Types/PendingVotes.agda, LibraBFT/Impl/IO/OBM/InputOutputHandlers.agda, LibraBFT/Impl/Types/ValidatorVerifier.agda, LibraBFT/ImplShared/Util/RWST.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda
This PR enables us to use `Either`, `Left` and `Right` in Agda so that we can model Haskell code more faithfully.
It also restates `⊎-elim*` in terms of functions available in the standard library; this required a little reordering in `LibraBFT.Prelude`.
Thanks @cwjnkins for the input.
=> Establish `Either`, `Left` and `Right` as aliases for `⊎`, `inj₁` and `inj₂` to enable more faithful model of Haskell code

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/ConsensusTypes/QuorumCert.agda, LibraBFT/Impl/Consensus/Liveness/ProposerElection.agda, LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Consensus/PersistentLivenessStorage.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/Consensus/Types/PendingVotes.agda, LibraBFT/Impl/Consensus/Types/PendingVotesSpec.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/IO/OBM/InputOutputHandlers.agda, LibraBFT/Impl/OBM/Logging/Logging.agda, LibraBFT/ImplFake/Consensus/RoundManager.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Util/RWST.agda, LibraBFT/ImplShared/Util/RWST/Syntax.agda, LibraBFT/ImplShared/Util/Util.agda, LibraBFT/Prelude.agda
This PR also:
- adds a `Monad` record opened with Agda's instance arguments, to simulate Haskell's type classes (this allows us to use do-notation for `Either` as well as `LBFT`)
- moves the convenient syntax for do-notation with `RWST` to its own file. This module is imported publicly by `LibraBFT/ImplShared/Util/Util.agda`, so many occurrences of `open RWST-do` have been removed from the implementation models.
- replaces some `if` and `case` statements with the branching operators of the new `RWST` datatype
- removes `ErrLog` and replaces all remaining occurrences with `FakeErr`
=> Overhaul the `RWST` monad and add support for reasoning with Dijkstra's weakest precondition calculus.

LibraBFT/Impl/Consensus/Types/PendingVotes.agda, LibraBFT/Impl/OBM/Crypto.agda, LibraBFT/Impl/Types/LedgerInfoWithSignatures.agda, LibraBFT/Impl/Types/ValidatorVerifier.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/Prelude.agda
This implements `LedgerInfoWithSignatures.verifySignatures`
That required implementing
- various validation functions in `ValidatorVerifier`
- creating a `CryptoHash` typeclass with `sign` and `verify` functions in `LibraBFT.Impl.OBM.Crypto`
- implementing a `CryptoHash LedgerInfo` instance
- other instances will be created when needed
This is work based on the `mark-verifyqcm` branch.
=> implemented LedgerInfoWithSignatures.verifySignatures

LibraBFT/Impl/Consensus/Types/PendingVotes.agda, LibraBFT/Impl/OBM/Crypto.agda, LibraBFT/Impl/Types/LedgerInfoWithSignatures.agda, LibraBFT/Impl/Types/ValidatorVerifier.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/Prelude.agda
This PR supersedes #60, which was done against the wrong branch (@msmoir's fault).
This implements `LedgerInfoWithSignatures.verifySignatures`
That required implementing
- various validation functions in `ValidatorVerifier`
- creating a `CryptoHash` typeclass with `sign` and `verify` functions in `LibraBFT.Impl.OBM.Crypto`
- implementing a `CryptoHash LedgerInfo` instance
- other instances will be created when needed
Also includes the following to make the Agda more closely model the Haskell:
- define and use `forM_`
- made `fakeErr` a real data type (to be renamed `ErrLog` in a future pull request)
- use the new `fakeErr` constructor in `ValidatorVerifier` and `PendingVotes`
- defined and used `foldrM`
- add a `Monad` instance for `Maybe`, and use `<$>` and `<*>` enabled by this
=> Implemented LedgerInfoWithSignatures.verifySignatures, various improvements to make Agda code more like Haskell code

LibraBFT/Impl/Consensus/ConsensusTypes/Block.agda, LibraBFT/Impl/Consensus/ConsensusTypes/VoteData.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/RoundManager/PropertyDefs.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/OBM/Logging/Logging.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/ImplShared/Util/RWST/Syntax.agda, LibraBFT/ImplShared/Util/Util.agda, LibraBFT/Prelude.agda, Optics/Functorial.agda
This PR adds info logging to the functions in `SafetyRules`, and re-does the proofs from `chris-dijkstra-monad` to account for these changes.
=> Logging in, and proofs about, `LibraBFT.Impl.Consensus.SafetyRules.SafetyRules`

LibraBFT/Impl/Handle.agda, LibraBFT/Impl/IO/OBM/InputOutputHandlers.agda, LibraBFT/Impl/Types/ValidatorSigner.agda
We have agreed that ALL new files will not indent the top level module, e.g.,
```
module foo where
stuff (not indented)
more stuff
```
This commit "fixes" 3 new files that were still indenting.
=> fix top level indent of 3 new Impl files

LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochDep.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
- `RoundManager.processVoteM`
- replaced a stub with a real call to `ProposerElection.isValidProposer`
- this required implementing `rmPgAuthor` in `ImplShared.Consensus.Types`
- NOTE: in Haskell this is a getter only lens `pgAuthor` whereas in Agda I have made it a function.
- Do we have a way to define getter only?
- replaced a stub with a real call to `BlockStore.getQuorumCertForBlock`
- the stub was written before `rmGetBlockStore` existed so now can be replaced
- `RoundManager.addVoteM`
- use `rmGetBlockStore`
- this required adding various fields, lens and functions to timeout data
- CHRIS: there is a note in the code pointing out a type checking problem I could use help on.
=> finish parts of RoundManager processVoteM

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/ConsensusTypes/ExecutedBlock.agda, LibraBFT/Impl/Consensus/Liveness/Properties/ProposerElection.agda, LibraBFT/Impl/Consensus/Liveness/ProposerElection.agda, LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Consensus/PersistentLivenessStorage/Properties.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/RoundManager/PropertyDefs.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochDep.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/ImplShared/Util/Util.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda
This PR contains proofs for the above-mentioned functions in `RoundManager.agda`, meant to help in proving `VotesOnce`. It also contains an change to the implementation that mirrors a change made today in the Haskell prototype.
=> RoundManager proofs (`executeAndVoteM`, `processProposalM`)

LibraBFT/Impl/Consensus/Liveness/ProposerElection.agda, LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Consensus/Network/Properties.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/RoundManager/PropertyDefs.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/ImplShared/Util/RWST.agda, LibraBFT/ImplShared/Util/Util.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda
This PR adds `LibraBFT.Impl.Handle.Properties`, and the main proof there is of the following system invariant: the two different `Epoch` fields in `RoundManager` remain the same. This relies on a postulated contract for `handleProposal` which is based on existing proofs for related `RoundManager` functions for processing a proposal.
This PR also adds:
- Some proof utilities for `RWST` and `LBFT`
- a `ToBool`-polymorphic `not`
- an `Eq` type class
- a new lemma about `List-filter`
- changes to the initial `RoundManager` for all peers (more fields populated)
=> Proof that the two Epoch fields of `RoundManager` stay the same, and misc.

LibraBFT/Base/KVMap.agda, LibraBFT/Hash.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/PersistentLivenessStorage.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochDep.agda, LibraBFT/Prelude.agda
- `LibraBFT/Impl/Consensus/BlockStorage/BlockStore`
- implemented `executeAndInsertBlockE`, `executeBlockE`, `getBlock`, `pathFromRoot`
- `LibraBFT/Impl/Consensus/BlockStorage/BlockTree`
- implemented `pathFromRoot`, `insertBlockE`
- postulated `addChild`
- `LibraBFT/ImplShared/Consensus/Types/EpochDep`
- implemented `btGetLinkableBlock`, `btGetBlock`, `btRoot`, `bsRoot`
- `LibraBFT/Prelude`
- implemented non-dependent `eitherS`
- implemented `forM'`
- `LibraBFT/Base/KVMap`
- postulated `insert`
- `LibraBFT/Hash`
- added `Eq-Hash` instance
- `LibraBFT/Impl/Consensus/PersistentLivenessStorage`
- postulated `saveTreeE`
=> implemented executeAndInsertBlockE and friends

LibraBFT/Impl/Consensus/ConsensusTypes/ExecutedBlock.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Properties/QuorumCert.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Properties/VoteData.agda, LibraBFT/Impl/Consensus/ConsensusTypes/QuorumCert.agda, LibraBFT/Impl/Consensus/ConsensusTypes/VoteData.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/Execution/ExecutorTypes/StateComputeResult.agda, LibraBFT/Impl/OBM/Crypto.agda, LibraBFT/Impl/OBM/Logging/Logging.agda, LibraBFT/Impl/Types/Properties/LedgerInfoWithSignatures.agda, LibraBFT/ImplFake/Consensus/RoundManager.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Util/Crypto.agda, LibraBFT/Prelude.agda
Restated the contract for `verifyQcM`  to something that actually holds, and prove it and some related properties it depends on.  This required fleshing out various pieces of implementation.  Restating the contract for `verifyQcM` broke the proof for `continue1.contract`; it is commented out in this PR and is already proved in another branch building on `chris-roundmanager-proofs`.
Implementation pieces fleshed out:
* `LibraBFT.Impl.Consensus.ConsensusTypes.Block`
* `LibraBFT.Impl.Consensus.ConsensusTypes.ExecutedBlock`
* `LibraBFT.Impl.Consensus.ConsensusTypes.QuorumCert`
* `LibraBFT.Impl.Consensus.ConsensusTypes.VoteData`
* `LibraBFT.Impl.Execution.ExecutorTypes.StateComputeResult`
* `LibraBFT.ImplShared.Consensus.Types`
* `LibraBFT.ImplShared.Consensus.Types.EpochIndep`
Properties …
=> Restate and prove contract for `verifyqQcM` plus more implementation and properties needed for that

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/ConsensusTypes/QuorumCert.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/IO/OBM/InputOutputHandlers.agda, LibraBFT/Impl/OBM/Logging/Logging.agda, LibraBFT/Impl/Types/LedgerInfoWithSignatures.agda
- `logErr` and `logInfo`
- take an arg (like Haskell)
- `withErrCtx`
- renamed from `withErrCtxt` (to be like Haskell)
- take an arg (like Haskell)
- `withErrCtx'`
- implemented and used
- `logEE`
- take an arg (like Haskell)
@cwjnkins please check the change in `RoundManager.Properties`
=> make logging align with Haskell version

LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda
@cwjnkins
at the appropriate time, please switch the code to use `extensionCheck` (instead of `extensionCheckM`, which should then be deleted).
=> SafetyRules.extensionCheck

LibraBFT/Impl/Consensus/ConsensusTypes/ProposalMsg.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Vote.agda, LibraBFT/Impl/Consensus/ConsensusTypes/VoteMsg.agda, LibraBFT/Impl/Consensus/Network.agda, LibraBFT/Impl/IO/OBM/InputOutputHandlers.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
This PR implements `processProposal` and `processVote` in `LibraBFT.Impl.Consensus.Network.agda` and removes the remaining hole in `LibraBFT.Impl.IO.OBM.InputOutputHandlers.agda`.
=> Fully connect `handle` in `InputOutputHandlers` to `RoundManager`

LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Properties/Util.agda
The PR fixes a few definitions and lemmas concerning properties of peer handler outputs that arose when adding sync info messages.
=> Fixes to `LibraBFT.Impl.Properties.Util.agda`

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Vote.agda, LibraBFT/Impl/Consensus/Liveness/ProposalGenerator.agda, LibraBFT/Impl/Consensus/Liveness/ProposerElection.agda, LibraBFT/Impl/Consensus/Liveness/RoundState.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/Consensus/Types/PendingVotes.agda, LibraBFT/ImplFake/Consensus/RoundManager.agda, LibraBFT/ImplFake/Consensus/RoundManager/Properties.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/ImplShared/Util/Crypto.agda, LibraBFT/ImplShared/Util/RWST/Syntax.agda
main work:
- RoundManager
- implement processSyncInfoMsgM
- implement processLocalTimeoutM
required for above:
- EpochIndep
- rearrange Timeout/TimeoutCertificate so defined before used
- add SyncInfo._siHighestTimeoutCert field
- add various lens related to that field
- BlockStore.syncInfoM
- add bsHighestTimeoutCert to SyncInfo.new
- Properties/BlockStore
- add bsHighestTimeoutCert to SyncInfo.new
- update contract *****
- Vote
postulate addTimeoutSignature
- ProposalGenerator
- postulate generateNilBlockM
- RoundState
- postulate processLocalTimeoutM
- rename recordVote to recordVoteM
- RoundManager/Properties.agda
- add bsHighestTimeoutCert
- SafetyRules
- postulate signTimeoutM
- ImplFake/Consensus/RoundManager
- deal with btHighestTimeoutCert
- …
=> impl RoundManager processSyncInfoMsgM; processLocalTimeoutM

LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/Prelude.agda
Here is some progress on extending the `handleProposalSpec.Contract` to ensure `OutputQc∈RoundManager`, and then use it together with `qcVoteSigsSentB4` to prove one of the `TODO`s in `VotesOnce`.  It required generalising various properties.  I've left some postulates, `obm-dangerous-magic!`, etc., but I think they should all be provable.
=> Add `OutputQc∈RoundManager` to `handleProposalSpec.Contract`, use it to prove one of the `qcVoteSigsSentB4` cases

LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/Common.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/Yasm/System.agda
As I mentioned in PR #94, it will not be true of the final implementation that `ensureRoundAndSyncUpM` sends not output messages. I have reverted these contract changes, and many of the accompanying changes to lemmas in `LibraBFT.Impl.Properties.Util.agda` I have also repaired and simplified the case of `newVote⇒lv≡` in `LibraBFT.Impl.Properties.VotesOnce.agda` proved in PR #94 .
=> Revert changes to RoundManager output contracts introduced in PR #94

LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/InputOutputHandlers.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/Common.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/Prelude.agda
Updated the proof of `invariantsCorrect` now that "round manager QC votes have had their signatures sent before" is tracked as a property preserved by peer handler steps.
Also merged in `chris-handle-vote-spec` (which postulates the contract for `handleVote`, so that more progress can be made on the other cases for the `VotesOnce` property)
=> Progress on proving that round manager QC votes have had their signatures sent before

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/ImplShared/Util/RWST/Syntax.agda
PR 
https://github.com/oracle/bft-consensus-agda/pull/103 
renamed `maybeS` to `maybeS-RWST`
and defined a new general "monadic" `maybeS`
This PR replaces some existing uses of `maybeS` in the `LBFT` monad with `maybeS-RWST`
IMPORTANT: See the comment in `Syntax.agda` on when to use the `-RWST` variant.
=> use maybe-RWST

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Properties/SyncInfo.agda, LibraBFT/Impl/Consensus/ConsensusTypes/SyncInfo.agda, LibraBFT/Impl/Consensus/ConsensusTypes/SyncInfo/Properties.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/ImplShared/Util/RWST/Syntax.agda
* Merge in `main`
* Change `SyncInfo.Contract` to propagate `QC.Contract` up, don't try to convert to abstract `IsValidQC` yet; we need to do that in context of `Preserves RoundManagerInv` because we need the `RoundManager-correct` to construct an abstract `EpochConfig`
* Similarly for `highestCommitCert` (except deal with `Maybe QuorumCert`)
* Move `SyncInfo.Properties` to `Properties.SyncInfo`, consistent with others
* Prove `ensureRoundAndSyncUpMSpec.contract`
=> Modify `SyncInfo.Contract`, prove `ensureRoundAndSyncUpMSpec.contract`

LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/Common.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/Lemmas.agda, LibraBFT/Prelude.agda, LibraBFT/Yasm/System.agda
This PR clarifies what I meant by my earlier comment that the message pool mentioned in the type of `RoundManagerInv`, in the proof of `invariantsCorrect`, should be the pool _prior_ to the last step of the system. It also contains progress and some cleanup for the parts of the peer handler contracts used to prove `qcVoteSigsSentB4`
=> Reworked `qcVoteSigsSentB4` proof, progress on contract for `ensureRoundAndSyncUpM`

LibraBFT/Impl/Consensus/BlockStorage/BlockRetriever.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/SyncManager.agda, LibraBFT/Impl/Consensus/PersistentLivenessStorage.agda, LibraBFT/Impl/Consensus/RecoveryData.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Util/RWST/Syntax.agda, LibraBFT/Prelude.agda
This implements the majority of NeedFetch/catchup.
A subsequent PR will implement the things postulated here.
- BlockRetriever (new file)
- postulate retrieveBlockForQCM
- BlockStore
- postulate rebuildM
- implement blockExists
- SyncManager
- implement needSyncForQuorumCert, needFetchForQuorumCert, fetchQuorumCertM
- implement syncToHighestCommitCertM, fastForwardSync
- RecoveryData (new file)
- EpochIndep
- define RootInfo, RootMetadata, RecoveryData, LedgerRecoveryData
- PersistentLivenessStorage
- postulate saveTreeM, startM
- Syntax
- define eitherS-RWST
- Prelude
- fix eitherS type
- implement !?
=> NeedFetch aka "catchup"

LibraBFT/Impl/Consensus/BlockStorage/Properties/SyncManager.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Properties/SyncInfo.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/VotesOnce.agda
* Refactoring to enable proving all `qvVoteSigSentB4` cases in `VotesOnce` proof, and do it
* Make `handleVoteSpec.Contract` independent of pool, like handleProposalSpec.Contract`
* Remove now-unnecessary pool argument from various Contracts
* Refactor `qcVoteSigsSentB4`
* Other small edits
=> Extend `handleProposalMsg` approach to `handleVoteMsg`, eliminate Contracts' dependence on message pool, various refactoring

LibraBFT/Impl/Consensus/BlockStorage/BlockRetriever.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/ConsensusTypes/BlockRetrieval.agda, LibraBFT/Impl/Consensus/LedgerRecoveryData.agda, LibraBFT/Impl/Consensus/PersistentLivenessStorage.agda, LibraBFT/Impl/Consensus/RecoveryData.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/IO/OBM/ObmNeedFetch.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
This is a continuation of https://github.com/oracle/bft-consensus-agda/pull/112
There will a continuation of this PR too - the newly postulated stuff.
- BlockRetriever
- implement retrieveBlockForQCM
- BlockStore
- postulate build
- implement rebuildM
- BlockTree
- implement getAllBlockIdM
- BlockRetrieval.agda NEW FILE
- postulate verify
- LedgerRecoveryData.agda NEW FILE
- postulate findRoot
- PersistentLivenessStorage
- postulate pruneTreeM
- RecoveryData
- implement findBlocksToPrune
- implement new
- RoundManager
- implement processBlockRetrievalRequestM
- ObmNeedFetch.agda NEW FILE
- postulate writeRequestReadResponseUNSAFE
=> need fetch continued

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/ImplShared/Consensus/Types.agda
added comment about StateComputer.compute not throwing exception nor maintaining state (but the possibility these may happen in the future)
Changed existing exception `ErrBlockNotFound` to `ErrCBlockNotFound` - that is used when the consensus level cannot find an expected block.
Added `ErrECCBlockNotFound` - that would be used inside the state computer, inside its "execution correction client".  It is never thrown in the Agda code (nor in the Haskell code).   But it is caught in `BlockStore.executeAndInsertBlockM`.  See the comment there.
=> StateComputer.compute state/exceptions

LibraBFT/Impl/Consensus/BlockStorage/BlockRetriever.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/ConsensusTypes/Block.agda, LibraBFT/Impl/Consensus/ConsensusTypes/BlockRetrieval.agda, LibraBFT/Impl/Consensus/ConsensusTypes/QuorumCert.agda, LibraBFT/Impl/Consensus/LedgerRecoveryData.agda, LibraBFT/Impl/Consensus/PendingVotes.agda, LibraBFT/Impl/Consensus/RecoveryData.agda, LibraBFT/Impl/Consensus/RoundManager.agda, LibraBFT/Impl/OBM/Rust/RustTypes.agda, LibraBFT/Impl/Types/ValidatorVerifier.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Interface/Output.agda, LibraBFT/Prelude.agda
This is a continuation of https://github.com/oracle/bft-consensus-agda/pull/117
It is the last NeedFetch PR.
- defined Output . SendBRP
- finished RoundManager.processBlockRetrievalRequestM so that is does SendBRP
- implement BlockStore.build
- BlockTree
- implement new
- postulate linkableBlockNew
- postulate Block.makeGenesisBlockFromLedgerInfo
- implement BlockRetrieval.verify
- postulate QuorumCert.certificateForGenesisFromLedgerInfo
- LedgerRecoveryData
- implement findRoot
- postulate several "library" functions
- RecoveryData.new : update to handle LedgerRecoveryData.findRoot errors
- RustTypes : define and use (and move some things from EpochIndep to here)
- EpochIndep
- implement liEndsEpoch, bRound, equality instance on BlockRetrievalStatus
- removed PendingVotes field from …
=> NeedFetch continued3

LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda
@cwjnkins. I made progress by refining and proving `pf3`, but I did not prove its requirements.  These can presumably be proved, but I couldn't quickly/easily do it.  I think the way I defined ( `bt₃` and) `il₃` has caused a lot of unnecessary pain, so I am stopping here.  I think this provides good motivation for the weakest precondition infrastructure you have suggested for the `Error` monad :smile:.  Feedback/input welcome.
=> Refine and prove `pf3`, comment on issue with defining `il3`

LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda, LibraBFT/Impl/Properties/Util.agda
Converted `insertQuorumCertE` to use the `EitherD` monad and prove a contract for it.  TODO: replace trivial proof obligation for "preserves existing QCs" and update the proof.
=> Convert `insertQuorumCertE` to `EitherD` and prove contract

LibraBFT/Impl/Consensus/ConsensusTypes/Block.agda, LibraBFT/Impl/Consensus/ConsensusTypes/BlockData.agda, LibraBFT/Impl/Consensus/ConsensusTypes/QuorumCert.agda, LibraBFT/Impl/Consensus/EpochManagerTypes.agda, LibraBFT/Impl/Consensus/LedgerRecoveryData.agda, LibraBFT/Impl/Consensus/Liveness/ProposalGenerator.agda, LibraBFT/Impl/Consensus/MetricsSafetyRules.agda, LibraBFT/Impl/Consensus/SafetyRules/PersistentSafetyStorage.agda, LibraBFT/Impl/Consensus/SafetyRules/SafetyRules.agda, LibraBFT/Impl/Consensus/TestUtils/MockStorage.agda, LibraBFT/Impl/Crypto/Crypto/Hash.agda, LibraBFT/Impl/OBM/Crypto.agda, LibraBFT/Impl/Types/ValidatorSigner.agda, LibraBFT/Impl/Types/Waypoint.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda
I started this work by looking for postulated things used by epoch change.
Writing those postulates led to writing new functions and new postulates (to be handled in a future PR).
- Block
- implemented makeGenesisBlockFromLedgerInfo, newNil
- BlockData
- implemented newGenesis, newGenesisFromLedgerInfo, newNil
- QuorumCert
- implemented certificateForGenesisFromLedgerInfo
- EpochManagerTypes
- added record ConsensusState
- LedgerRecoveryData.agda
- update to handle Either from Block.makeGenesisBlockFromLedgerInfo
- ProposalGenerator
- implement generateNilBlockM
- MetricsSafetyRules
- implement performInitialize
- PersistentSafetyStorage
- implement consensusKeyForVersion
- SafetyRules
- implement consensusState, initialize
- MockStorage
- implement retrieveEpochChangeProofE
- …
=> functions needed by epoch change

LibraBFT/Impl/Consensus/StateComputerByteString.agda
(made because Haskell main was out-of-date with my local)
=> replaced inaccurate comment 

LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/ConsensusProvider.agda, LibraBFT/Impl/Consensus/EpochManager.agda, LibraBFT/Impl/Consensus/EpochManagerTypes.agda, LibraBFT/Impl/IO/OBM/GenKeyFile.agda, LibraBFT/Impl/OBM/ConfigHardCoded.agda, LibraBFT/Impl/OBM/Logging/Logging.agda, LibraBFT/Impl/Storage/DiemDB/DiemDB.agda, LibraBFT/Impl/Storage/DiemDB/LedgerStore/LedgerStore.agda, LibraBFT/Impl/Types/OnChainConfig/ValidatorSet.agda, LibraBFT/Impl/Types/ValidatorSigner.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/Prelude.agda
ConsensusProvider is used for system initialization.
DiemDB and LedgerStore are used for epoch change.
This PR is built on top of PR https://github.com/oracle/bft-consensus-agda/pull/149
=> implement ConsensusProvider, DiemDB and LedgerStore

LibraBFT/Impl/Storage/DiemDB/DiemDB.agda
Modified the Haskell code for `DiemDB.saveTransactions` so we could make the Agda align better and more conveniently, then combined steps not needed because only one contains a conditional branch.
=> Streamline `EitherD` variants for `DiemDB.saveTransactions`

LibraBFT/Base/KVMap.agda, LibraBFT/Impl/Consensus/EpochManager.agda, LibraBFT/Impl/Consensus/TestUtils/MockStorage.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/GenKeyFile.agda, LibraBFT/Impl/IO/OBM/Start.agda, LibraBFT/Impl/OBM/Genesis.agda, LibraBFT/Impl/OBM/Init.agda, LibraBFT/Impl/OBM/Util.agda, LibraBFT/Impl/Types/BlockInfo.agda, LibraBFT/Impl/Types/LedgerInfo.agda, LibraBFT/Impl/Types/LedgerInfoWithSignatures.agda, LibraBFT/Impl/Types/OnChainConfig/ValidatorSet.agda, LibraBFT/Impl/Types/ValidatorVerifier.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/Prelude.agda
Besides the following specific changes, many functions were changed
in Haskell and Agda to return Either ErrLog * instead of using errorExit
Impl/Handle
- initEMWithOutput
- initRMWithOutput
Impl/OBM/Init : new file
- initialize : top level bootstrap initialization entry point (calls the following):
ConsensusProvider : new file
- top level bootstrap initialization entry point called by OBM.Init
GenKeyFile : new file
- generates keys
- creates ValidatorVerifier (i.e., other node's public keys)
- create  ValidatorSigner   (i.e., this node's secret keys)
Genesis : new file : used during initialization
- obmMkGenesisLedgerInfoWithSignatures
- obmMkLedgerInfoWithEpochState vs = do
Impl/OBM/Util : new file
- checkBftAndRun : checks given number of nodes can handle given number of failures (1 …
=> initialization

LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Handle.agda, LibraBFT/Impl/Handle/InitProperties.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/GenKeyFile.agda, LibraBFT/Impl/OBM/Init.agda, LibraBFT/Impl/Properties/Common.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplFake/Handle.agda, LibraBFT/ImplFake/Handle/Properties.agda, LibraBFT/ImplFake/Properties.agda, LibraBFT/ImplFake/Properties/VotesOnceDirect.agda, LibraBFT/ImplShared/Consensus/Types.agda, LibraBFT/ImplShared/Consensus/Types/EpochDep.agda
prefix a LOT of stuff with `fake` to make it easier to identify and remove later
Impl/Handle
- prove EitherD/Either versions of initEMWithOutput are equivalent
- fake renames
- reordered stuff in file
Impl/Handle/InitProperties
- new file
- initial shot at contract
=> prove EitherD/Either versions of init equivalent; init contract

LibraBFT/Base/KVMap.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda, LibraBFT/Impl/Consensus/EpochManager.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Util/Crypto.agda, LibraBFT/ImplShared/Util/Dijkstra/EitherD.agda, docs/PeerHandlerContracts.org
This is the first of two closely related PRs.  This one refines the contract for `insertBlockESpec`, providing it with `Requirements` that will be needed to prove its contract.  The [next one](#148) refactors that, so that each part of the contract is provided with only the prerequisite properties that its proof is expected to require.
This one also:
* reinstates the `stateComputerResult` that broke the proof in`executeAndInsertBlockE`, fixes that proof, and documents it in a little more detail for "tutorial" purposes; also updates the description in `PeerHandlerContracts.org` accordingly.
* Establishes some utility types for more clearly expressing requirements relating `Block`s and their ids.
* Refines the notion of two `Block`s being "equivalent" (`_≈Block_`), so that it does not …
=> Start refining `insertBlockESpec`

LibraBFT/Abstract/Properties.agda, LibraBFT/Abstract/RecordChain.agda, LibraBFT/Abstract/RecordChain/Assumptions.agda, LibraBFT/Abstract/RecordChain/Properties.agda, LibraBFT/Abstract/Records/Extends.agda, LibraBFT/Abstract/System.agda, LibraBFT/Base/KVMap.agda, LibraBFT/Concrete/Obligations/PreferredRound.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/SyncManager.agda, LibraBFT/Impl/Consensus/EpochManager.agda, LibraBFT/Impl/Consensus/Network/Properties.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Util/Crypto.agda, LibraBFT/ImplShared/Util/Dijkstra/EitherD.agda, LibraBFT/ImplShared/Util/Dijkstra/RWS.agda, LibraBFT/ImplShared/Util/HashCollisions.agda, LibraBFT/Prelude.agda, Optics/Functorial.agda, docs/PeerHandlerContracts.org
This pull request makes the `Abstract` properties hold unless they can provide a specific example of noninjectivity of abstract `Block`s that are "in the system".  This removes the possibility for the proofs to cheat by simply creating a pair of different `Block`s with the same `bId`, which is trivial without the requirement to show that those `Block`s are considered to be "in the system" by whomever is instantiating the `Abstract` properties.
This is pushed all the way through for our main correctness property `CommitsDoNotConflict`, and only partially for the extended properties that lack `RecordChain`s in which all `Record`s are known to be `InSys`.  This is because we cannot prove that the injectivity failures are `InSys` unless and until we model someone attempting to convince …
=> Connect injectivity failures to data "in the system" 

LibraBFT/Abstract/Properties.agda, LibraBFT/Abstract/RecordChain.agda, LibraBFT/Abstract/RecordChain/Assumptions.agda, LibraBFT/Abstract/RecordChain/Properties.agda, LibraBFT/Abstract/Records/Extends.agda, LibraBFT/Abstract/System.agda, LibraBFT/Concrete/Obligations/PreferredRound.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Prelude.agda
This pull request makes the `Abstract` properties hold unless they can provide a specific example of noninjectivity of abstract `Block`s that are "in the system", according to a predicate provided as a module parameter.  This removes the possibility for the proofs to cheat by simply creating a pair of different `Block`s with the same `bId`, which is trivial without the requirement to show that those `Block`s are considered to be "in the system" by whomever is instantiating the `Abstract` properties.  The top-level `Abstract` modules now take a module parameter that asserts that there are no injectivity failures among `Record`s that are "in the system", which allows us to eliminate the possibility of such an injectivity failure., yielding the desired correctness properties.  We have yet to …
=> Make `Abstract` module provide evidence of specific injectivity failure

LibraBFT/Abstract/Properties.agda, LibraBFT/Abstract/RecordChain.agda, LibraBFT/Abstract/RecordChain/Assumptions.agda, LibraBFT/Abstract/RecordChain/Properties.agda, LibraBFT/Abstract/Records/Extends.agda, LibraBFT/Abstract/System.agda, LibraBFT/Base/KVMap.agda, LibraBFT/Concrete/Obligations/PreferredRound.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda, LibraBFT/Impl/Consensus/BlockStorage/Properties/SyncManager.agda, LibraBFT/Impl/Consensus/Network/Properties.agda, LibraBFT/Impl/Consensus/RoundManager/Properties.agda, LibraBFT/Impl/Consensus/SafetyRules/Properties/SafetyRules.agda, LibraBFT/Impl/Handle/Properties.agda, LibraBFT/Impl/IO/OBM/Properties/InputOutputHandlers.agda, LibraBFT/Impl/Properties/Util.agda, LibraBFT/Impl/Properties/VotesOnce.agda, LibraBFT/ImplShared/Consensus/Types/EpochIndep.agda, LibraBFT/ImplShared/Util/Crypto.agda, LibraBFT/ImplShared/Util/HashCollisions.agda, LibraBFT/Prelude.agda, Optics/Functorial.agda, docs/PeerHandlerContracts.org
So far, our proofs depend on an assumption that hash collisions don't exist. But they do! We have required hash collisions to be put in context of a ReachableSystemState just to remind ourselves that we cannot assume lack of hash collisions "for free". But this did not mean much because nothing connected the specific hash collisions to that ReachableSystemState.
This PR makes the first steps towards doing so, dealing with one important class of potential hash collisions: those on BlockIds, requiring properties to depend only on the assumption that these hash collisions do not exist in the specific state for which a property is proved. This is achieved by defining a notion of a hash being in the state (e.g., a Proposal that has the same hash as a Block already stored in the BlockTree, but …
=> Make `Impl` properties identify specific hash collisions

LibraBFT/Abstract/RecordChain/Assumptions.agda, LibraBFT/Abstract/RecordChain/Properties.agda, LibraBFT/Concrete/Obligations.agda, LibraBFT/Concrete/Obligations/PreferredRound.agda, LibraBFT/Concrete/Properties.agda, LibraBFT/Concrete/Properties/PreferredRound.agda, LibraBFT/Concrete/Properties/VotesOnce.agda, LibraBFT/Concrete/System.agda
This PR augments the proofs in the `Concrete` modules to ensure that any injectivity failures they
claim are accompanied by evidence that the `Block`s involved in that failure are "in the system"
(i.e., have actually been sent during the execution of the system).  Otherwise, it would be trivial
to prove these properties simply by constructing a pair of different abstract `Block`s that have the
same `Block` id, which is trivial.
The `Concrete.*` modules build on the `Abstract.*` modules to specify implementation obligations that
are closer to the actual implementation than the `Abstract` modules.  In particular, it reduces the
obligations to the level of obligations for honest peers sending `Vote`s, whereas the `Abstract` modules
specify obligations in terms of `Record`s (`Block`s and …
=> Extend evidence that injectivity failures are `InSys` across `Concrete` modules

src/Dijkstra/EitherD.agda, src/Dijkstra/EitherD/Syntax.agda, src/Dijkstra/RWS.agda, src/Dijkstra/RWS/Syntax.agda, src/Dijkstra/Syntax.agda, src/Haskell/Modules/RWS.agda, src/LibraBFT/Prelude.agda
Our preference for switched argument order for `eitherSD` and `maybeSD` is application-specific, and inconsistent with traditional Haskell order.  This pull request will clean this up by making the `Haskell` and `Dijkstra` "sub repos" consistent with traditional order.
Note: so far, only `eitherSD` -> `eitherD` has been done.  I'm seeking feedback first.  @haroldcarr
=> Make `EitherD-[either|maybe]` consistent with traditional argument order

docs/PeerHandlerContracts.org, src/Dijkstra/EitherD.agda, src/LibraBFT/Impl/Consensus/BlockStorage/BlockStore.agda, src/LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, src/LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockStore.agda, src/LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda, src/LibraBFT/Impl/Consensus/RoundManager.agda, src/LibraBFT/Impl/Consensus/RoundManager/Properties.agda
* Prove that `EitherD-weakestPre m P` really is the weakest precondition required to ensure that predicate `P` holds for the result of running `EitherD` program `m`.  This is shown by proving that, for any `m : EitherD E A`, if `P (EitherD-run m)` holds, then `EitherD-weakestPre m P` holds.  This is stated as property `Post⇒wp`, and proved in `EitherD-wp-is-weakest`.
* Add an "original" version of `ensureRoundAndSyncUpM`, which looks almost identical to the original Haskell code, and provide a (trivial) proof that it is equivalent the the version that is broken into steps for proofs.  We do not intend to do so in all cases, because the correspondence is usually straightforward.  This demonstrates that we can do so when needed.
* Similarly for `insertBlockE`
* Update definitions of the …
=> Refine definitions of `Either` variants, proofs, prove that `EitherD-weakestPre` really is weakest, and update documentation

src/Dijkstra/AST.agda, src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Core.agda, src/Dijkstra/AST/Example.agda, src/Dijkstra/AST/RWS.agda, src/Dijkstra/AST/Syntax.agda, src/Dijkstra/RWS.agda, src/Haskell/Modules/FunctorApplicativeMonad.agda, src/Haskell/Modules/RWS.agda, src/Haskell/Prelude.agda
This PR contains a POC generalization of the repo's current approach to program verification. A single datatype, `AST`, can be instantiated to a type equivalent to the existing `RWS` or to one equivalent to `EitherD`. Furthermore, the work of adding predicate transformers for branching operations need not be repeated for each such instance (as is done in the code currently), but can be generically added to a set of `AST` operations.
=> Generalization of EitherD, RWS

src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Maybe.agda
This combines work done by @mark-moir, @haroldcarr and @cwjnkins to add `Either` and `Maybe` AST versions and prove required properties plus some examples.  I'm proposing to merge this to branch `chris-pr-189`, where we can continue this work before merging to `main`.
=> Add ASTs for `Either` and `Maybe`, along with examples and proofs

src/Dijkstra/AST/Maybe.agda
The hole that is left clearly has a contradiction:
- `e₂⇓0` says it evaluates to 0
- but `dom` for the `Div` returns `⊤`
- and `runMaybe  ⟦ e₂ ⟧` is claiming `just (Succ _)`
Can anyone provide hints on how to proceed?
=> proving soundness of partiality : still has hole

src/Dijkstra/AST/Maybe.agda, src/Dijkstra/AST/Maybe/Examples/Branching.agda, src/Dijkstra/AST/Maybe/Examples/Partiality.agda
The main purpose of this PR is to add an example illustrating the use of a branching extension using our framework.  Details:
* use framework to extend `MaybeD` with branching operations
* add an example program that uses them
* prove a property about the program
* factor `Partiality` out into a separate file under new `Examples` directory
* various minor simplifications and comments
=> An example demonstrating the use of branching extensions in `MaybeD`.

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Examples/Maybe/Branching.agda, src/Dijkstra/AST/Maybe.agda
This PR:
- adds some syntax support for branching operations for `AST MaybeExtOps`
- `ifAST_then_else_` and `eitherAST` and a variant `eitherSAST` with different argument order
-  simplifies and cleans up the `BCif` example and adds an `ifAST` version
-  adds an example for `BCeither` / `either[S]AST`
=> Add some syntax support for branching operations for `AST MaybeExtOps`, and some examples

src/Dijkstra/AST/Either.agda, src/LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, src/LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda
This PR:
* adds an `AST` version of `insertQuorumCertE`
* proves the contract for `insertQuorumCertE-AST`
The  `AST` version of `insertQuorumCertE` does *not* split into explicit steps, and I could do the proof nonetheless.  I think this indicates that the framework is having its desired effect of guiding the prover.  That said, this is hardly a rigorous user experience study, given that I was able to reuse parts of the previous proof, and had the experience of having proved it before.
=> Add `AST` version of `insertQuorumCertE`, prove its contract

src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Examples/Maybe/Bind.agda, src/Dijkstra/AST/Examples/Maybe/Partiality.agda, src/Dijkstra/AST/Maybe.agda, src/Dijkstra/AST/RWS.agda, src/LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda
This PR starts with an example created by @haroldcarr, with a simple `MaybeD` (should be renamed `MaybeAST`) program that includes two `bind`s using (unknown) `MaybeD` programs.  It then finishes the proof that came with the initial example, and along the way establishes a simpler example with only a single bind and proves it in a roundabout way, with documentation to help us  understand it.  It then postulates a lemma to make it easier to provide the proof obligations for `bind`s in `MaybeD`, and uses that lemma to also prove the two-bind example.  Finally, it begins the proof of this lemma, which is not quite finished as I am out of time.  The above-mentioned lemma is not quite satisfying because it requires explicitly specifying the "continuation" after the bind, which is cumbersome …
=> Work on Harold's `Maybe` `bind` example

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Examples/Either/Bind.agda, src/Dijkstra/AST/Examples/Maybe/Bind.agda, src/Dijkstra/AST/Examples/Maybe/Branching.agda, src/Dijkstra/AST/Examples/Maybe/Partiality.agda, src/Dijkstra/AST/Maybe.agda, src/Dijkstra/AST/RWS.agda, src/Dijkstra/AST/Syntax.agda, src/LibraBFT/Impl/Consensus/BlockStorage/BlockTree.agda, src/LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda
The purpose of this PR is to make it easier to use the framework, including branching operations.
Rather than considering the branching operations as "extensions" to an underlying ("base") AST, we
consider the version extended with branching operation as the first target, even for programs that
don't use branching operations (initially).  We then streamline the importing and opening of the
extended AST and associated properties, as demonstrated in the updated examples.  Finally, the
BlockTree definitions and proofs are updated to use the new style, demonstrating the simpler
importing/opening facilitated by this PR.
=> Make extended `AST` versions default, streamline their use, update examples and proofs

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Core.agda, src/Dijkstra/AST/RWS.agda
NOTE: This branch does not compile, as the changes have not been propagated to the AST versions of Either or Maybe. Feel free to mark it as a draft for now.
This PR reduces the number of monotonicity lemmas required from 5 to 3, by merging the two lemmas for bind into one and merging the two for operations into one. The purpose of this is to reduce the burden of proving these properties (and shrink the number of lines needed to list the record `ASTPredTransMono`)
=>  Consolidate monotonicity requirements

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Core.agda, src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Maybe.agda, src/Dijkstra/AST/RWS.agda
The main purpose of this PR is to provide general support for extending a "predTrans is weakest" proof for the base operations to one for the operations extended to support branching.  This eliminates the need to replicate the proofs for branching for each new monad supported.  There is also some formatting/alignment that should be easy to identify as such.
=> Enable extending "predTrans is weakest" proof from base to extended version

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/RWS.agda
Self explanatory.
Note that it builds on a commit with some opening and alignment, which I accidentally pushed directly to `christa-pr-223-mono-merge`.
=> Add `maybeAST` to `BranchingSyntax` and example from paper using it

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Examples/PaperIntro.agda, src/Dijkstra/AST/RWS.agda, src/LibraBFT/Impl/Consensus/BlockStorage/Properties/BlockTree.agda
The main purpose of this PR is to simplify the steps to generate the proof of the example in the paper, and to present it in  more detail, explaining how the framework generates the proof obligations.
While doing this, I noticed that the proof obligations for `opPT` for `BCmaybe` were in a different order (nothing then just) than `maybe` (just then nothing), so I reversed them and made relevant fixes.  Some will argue these should be two separate pull requests.  They would be right, but I don't want to send a breaking PR, nor spend time to tease them apart.
=> Rework paper intro example, simpler and more detail; reorder proof obligations for `maybe` to match arguments to `maybe`

src/Dijkstra/AST/Branching.agda, src/Dijkstra/AST/Core.agda, src/Dijkstra/AST/Either.agda, src/Dijkstra/AST/Examples/Either/Bind.agda, src/Dijkstra/AST/Examples/Maybe/Branching.agda, src/Dijkstra/AST/Maybe.agda, src/Dijkstra/AST/Prelude.agda, src/Dijkstra/AST/RWS.agda, src/Haskell/Modules/Either.agda
This PR contains no functional change, just formatting, naming, etc. for consistency with the paper (some changes made in the paper as well).
I'm creating the PR against branch `mark-make-ast-independent-of-haskell` so it's easy to review before #245 is merged, but it should be retargeted to `main-ast` after #245 is merged.
=> Formatting, comments, naming for consistency with paper. 
